#include "exit.h"
#include "config.h"

/* 
  外部控制退出循环 (Generated by Claude)
  函数：signal_handler, check_keep_file
*/
volatile sig_atomic_t keep_running = 1;

void signal_handler(int signum) {
    if (signum == SIGINT || signum == SIGTERM) {
        log_info("Received signal to terminate: %d", signum);
        keep_running = 0;
    }
}

int check_keep_file() {
    if (access(KEEP_FILE, F_OK) != 0) {
        log_info("Keep file removed...");
        keep_running = 0;
        return 1;
    }
    return 0;
}

// 清除文件
void cleanup_files(void) {
    if(remove(DATA_FILE_1) != 0) {
        log_error("删除 %s 失败", DATA_FILE_1);
    }
    if(remove(DATA_FILE_2) != 0) {
        log_error("删除 %s 失败", DATA_FILE_2);
    }
    if(remove(KEEP_FILE) != 0) {
        log_error("删除 %s 失败", KEEP_FILE);
    }

    log_info("文件清除完成");
}